import { StructuredConfigEditor } from '../components/StructuredConfigEditor';
import type { TemplateConfigField, TemplateConfigGroup } from './templateConfig';
import { errorRulesShape, nonemptyText, stringsShape, validateStructuredValueText, type ConfigShape, type ConfigText } from './structuredConfig';

export function structuredField(path: string[], label: ConfigText, shape: ConfigShape, description?: ConfigText): TemplateConfigField {
  return {
    path, label, type: 'custom', description, defaultValue: shape.type === 'array' ? [] : {},
    render: props => <StructuredConfigEditor {...props} shape={{ ...shape, label: shape.label ?? label }} />,
    validate: value => validateStructuredValueText(shape, value),
  };
}

const modelMatch: ConfigShape = { type: 'object', fields: {
  name: { ...nonemptyText, initial: '*', label: { zh: '模型名称或通配符', en: 'Model name or wildcard', ja: 'モデル名 / ワイルドカード' } },
  protocol: { type: 'select', optional: true, options: ['openai', 'gemini', 'claude', 'codex', 'antigravity'], label: { zh: '目标协议', en: 'Target protocol', ja: '送信先プロトコル' } },
  'from-protocol': { type: 'select', optional: true, options: ['openai', 'responses', 'gemini', 'claude'], label: { zh: '来源协议', en: 'Source protocol', ja: '送信元プロトコル' } },
  headers: { type: 'map', optional: true, item: { type: 'string' }, label: { zh: '请求头匹配（支持 *）', en: 'Header patterns (* supported)', ja: 'ヘッダーパターン（* 対応）' } },
  match: { type: 'array', optional: true, item: { type: 'map', item: { type: 'any' } }, label: { zh: 'JSON 路径值等于', en: 'JSON path values equal', ja: 'JSON パスが一致' } },
  'not-match': { type: 'array', optional: true, item: { type: 'map', item: { type: 'any' } }, label: { zh: 'JSON 路径值不等于', en: 'JSON path values do not equal', ja: 'JSON パスが不一致' } },
  exist: stringsShape({ zh: '必须存在的 JSON 路径', en: 'JSON paths that must exist', ja: '存在する JSON パス' }),
  'not-exist': stringsShape({ zh: '必须缺失的 JSON 路径', en: 'JSON paths that must be absent', ja: '存在しない JSON パス' }),
} };

export const payloadShape = (mode: string): ConfigShape => ({
  type: 'array', item: { type: 'object', fields: {
    models: { type: 'array', label: { zh: '匹配条件', en: 'Matching models', ja: '適用条件' }, item: modelMatch,
      initial: [{ name: '*' }], validate: value => Array.isArray(value) && value.length ? null : { zh: '请至少添加一个模型匹配条件', en: 'At least one model pattern is required', ja: 'モデルの適用条件を 1 件以上追加してください' } },
    params: mode === 'filter'
      ? { type: 'array', item: nonemptyText, label: { zh: '要删除的 JSON 路径', en: 'JSON paths to remove', ja: '削除する JSON パス' } }
      : { type: 'map', label: { zh: 'JSON 路径与参数值', en: 'JSON paths and values', ja: 'JSON パスと値' }, item: mode.endsWith('-raw')
        ? { type: 'any', validate: value => { if (typeof value !== 'string') return null; try { JSON.parse(value); return null; } catch { return { zh: '每个原始字符串都必须是有效 JSON（文本字面量需加双引号）', en: 'Each raw string must be valid JSON (quote string literals)', ja: '各 raw 文字列には有効な JSON を指定してください（文字列リテラルは引用符で囲みます）' }; } } }
        : { type: 'any' } },
  } },
});

export const payloadTemplateGroups: TemplateConfigGroup[] = [{
  id: 'request-payload', title: { zh: '请求参数规则', en: 'Request payload rules', ja: 'リクエストパラメータルール' },
  description: { zh: '按顺序设置默认值、覆盖或移除参数。模型名和请求头支持通配符；JSON 路径支持 gjson/sjson 语法。只修改需要调整的规则，其余规则（包括模型别名生成的规则）会保留。', en: 'Apply defaults, overrides and filters in order. Model and header patterns support wildcards; paths use gjson/sjson syntax. Existing rules, including rules generated by aliases, are retained until edited.', ja: '既定値・上書き・削除を順番に適用します。ワイルドカードと gjson/sjson パスに対応。別名から生成された既存ルールも維持します。' },
  fields: [
    ['default', { zh: '补充缺失参数', en: 'Default values', ja: '既定値' }],
    ['default-raw', { zh: '补充原始 JSON', en: 'Default raw JSON', ja: '既定の raw JSON' }],
    ['override', { zh: '覆盖参数', en: 'Override values', ja: '上書き' }],
    ['override-raw', { zh: '覆盖原始 JSON', en: 'Override raw JSON', ja: 'raw JSON の上書き' }],
    ['filter', { zh: '移除参数', en: 'Remove parameters', ja: 'パラメータの削除' }],
  ].map(([mode, label]) => structuredField(['requests', 'payload', mode as string], label as ConfigText, payloadShape(mode as string))),
}];

export { errorRulesShape };
